export const users = [
    { id: 1, name: 'Alice Smith', email: 'alice.smith@example.com', age: 28 },
    { id: 2, name: 'Bob Johnson', email: 'bob.johnson@example.com', age: 35 },
    { id: 3, name: 'Charlie Brown', email: 'charlie.brown@example.com', age: 22 },
    { id: 4, name: 'David Wilson', email: 'david.wilson@example.com', age: 31 },
    { id: 5, name: 'Eve Davis', email: 'eve.davis@example.com', age: 26 },
    { id: 6, name: 'Frank Miller', email: 'frank.miller@example.com', age: 40 },
    { id: 7, name: 'Grace Lee', email: 'grace.lee@example.com', age: 29 },
    { id: 8, name: 'Hannah Martinez', email: 'hannah.martinez@example.com', age: 33 },
    { id: 9, name: 'Ian Taylor', email: 'ian.taylor@example.com', age: 24 },
    { id: 10, name: 'Jane Moore', email: 'jane.moore@example.com', age: 27 },
    { id: 11, name: 'Kyle Anderson', email: 'kyle.anderson@example.com', age: 32 },
    { id: 12, name: 'Laura Thomas', email: 'laura.thomas@example.com', age: 30 },
    { id: 13, name: 'Mike Jackson', email: 'mike.jackson@example.com', age: 45 },
    { id: 14, name: 'Nina White', email: 'nina.white@example.com', age: 21 },
    { id: 15, name: 'Oscar Harris', email: 'oscar.harris@example.com', age: 38 },
    { id: 16, name: 'Paul Martin', email: 'paul.martin@example.com', age: 36 },
    { id: 17, name: 'Quinn Thompson', email: 'quinn.thompson@example.com', age: 23 },
    { id: 18, name: 'Rachel Garcia', email: 'rachel.garcia@example.com', age: 34 },
    { id: 19, name: 'Sam Clark', email: 'sam.clark@example.com', age: 28 },
    { id: 20, name: 'Tina Rodriguez', email: 'tina.rodriguez@example.com', age: 25 },
  ];
